version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: pip
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit amount of opened PRs
    open-pull-requests-limit: 10
    target-branch: "dependencies"
