version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "dependencies"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
    - "Type: Dependencies"
    - "Lang: Dockerfile"

  # Check for github actions dependences
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
