---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: check-toml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.2
    hooks:
      - id: markdownlint
        args: ["--fix"]
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.0
  #   hooks:
  #     - id: python-safety-dependencies-check
  #       files: pyproject.toml
  #       args: ['--disable-telemetry']
  - repo: https://github.com/jazzband/pip-tools
    rev: '6.0.0'
    hooks:
      - name: Build requirements.txt
        id: pip-compile
      - name: Build requirements-dev.txt
        id: pip-compile
        ar gs: ['requirements-dev.in', '--allow-unsafe']
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.21.0
    hooks:
      - id: yamllint
