site_name: Sal y Vinagre APPCC

nav:
  - Home: index.md
  - Presentación:
    - Introducción: intro/index.md
    - Legislación: intro/legislacion.md
    - Generalidades: intro/generalidades.md
    - Descripción de la actividad de la empresa: intro/descripcion.md
  - Planes:
    - Plan de Infraestructuras y Mantenimiento: planes/mantenimiento.md
    - Plan de Control del Agua: planes/agua.md
    - Plan de Limpieza y Desinfección: planes/limpieza.md
    - Plan de Control de Plagas: planes/plagas.md
    - Plan de Control de Proveedores: planes/proveedores.md
    - Plan de Formación: planes/formacion.md
    - Plan de Trazabilidad: planes/trazabilidad.md
    - Plan de Gestión de Residuos: planes/residuos.md
  - Anexos:
    - Listado de Manipuladores: anexos/manipuladores.md
    - Listado de Proveedores: anexos/proveedores.md
    - Recetario: anexos/recetario.md
    - Registro de Incidencias: anexos/incidencias.md
  - Lista de Cambios: ChangeLog.md

plugins:
  - search
  - markdownextradata

extra:
    rs: "Carlos Alberto Martín Pérez"
    nif: "09765745V"
    nc: "Sal y Vinagre"
    address: "Plaza del Mercado SN, planta Alta 64-65, 37001, Salamanca"
    raal: "201977/SA"
    actividad: "Minorista Polivalente"
