[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Carlos Martín", email = "inean.es@gmail.com"},
]
dependencies = [
    "mkdocs~=1.1",
    "mkdocs.markdownextradata-plugin~=0.2",

    "mkdocs-with-pdf~=0.8",
    "qrcode~=6.1",
]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
