---
name: Build
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master
  schedule:
    - cron: 11 06 * * *
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: Install extra system dependences
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install pygobject3
          brew install pango

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          enable-pep582: true
          cache: true

      # Only update requirements when running on dependencies branch
      - name: Update requirements
        if: "!contains(github.ref, 'dependencies')"
        run: pdm update --no-sync && pdm sync --clean

      - name: Install dependencies
        run: pdm install -v && pdm info

      - name: Build docs
        run: pdm run mkdocs build --strict

      # Reached this point, we can commit safely pdm.lock file
      - name: Commit files
        if: "!contains(github.ref, 'dependencies')"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pdm.lock
          git diff-index --quiet HEAD || git commit -m "Update dependencies"

      - name: Push changes
        if: "!contains(github.ref, 'dependencies')"
        uses: ad-m/github-push-action@master
        with:
          branch:  ${{ github.ref }}
