---
name: Docker
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - "Dockerfile"
      - "pdm.lock"
      - "pyproject.toml"
      - "docs/**/*.md"
  schedule:
      - cron: 11 06 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build .
      - name: List docker images
        run: |
          mkdir -p build_log
          docker image ls | tee ./build_log/docker_images.txt
      - uses: actions/upload-artifact@v2
        with:
          name: build-log-${{ matrix.target }}
          path: build_log
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}:${{ matrix.target }}'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: trivy-scan-${{ matrix.target }}
      #     path: trivy-results.sarif
